config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete', as: :sign_out

  get "/users/new" => 'users#new', as: :sign_up
  post "/users" => 'users#create', as: :users

  root 'home#dashboard'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.blank?
      redirect_to sign_in_path, notice: "Please Sign In"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!
  
  def dashboard
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #Get User, validate PW, and set session, then redirect

    email = params[:email]
    password = params[:password]

    user = User.find_by email: email
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:alert] = "Something is wrong with your email or password"
      render :new
    end

  end

  def delete
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:email, :password, :password_confirmation)
    if @user.save
      # sign in
      session[:user_id] = @user.id
      # redirect
      redirect_to root_path, notice: "Thanks for signing up! #secrets"
    else
      render :new
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/dashboard.html.erb
<h1>Home#dashboard</h1>
<p>Find me in app/views/home/dashboard.html.erb</p>

<h1 class="secret">#thesecret</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Week5TwitterPrep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <% if @current_user %>
    <div>
      <%= link_to 'Sign Out', sign_out_path, method: :delete %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>

  <% if notice %>
    <div class="alert alert-info"><%= notice %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>Users#new</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation, label: "Password Confirmation" %>
  <%= f.submit "Sign Up", class: "btn btn-primary btn-block btn-lg" %>
<% end %>

</div>